---
version: '3'
services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yamuna

  mywordpress:
    image: wordpress
    ports:
      - 8080:80
    deploy:
      replicas: 2
...
